"""Universe curation for the strategy-discovery rebuild (Phase 1 Q5).

Applies the brainstorm's Q5 criteria to a candidate pool:
  ~15 large-cap (top by market_cap)
  ~15 mid-cap (next by market_cap)
  ~10 high FDV/MC = total_supply / circulating_supply (highest dilution overhang)
  ~10 low turnover = volume_24h / market_cap (lowest velocity)
All filtered to require >= 6 months of 1h OHLCV AND CoinPaprika supply data.

Pure ranking logic + CLI. No HTTP calls inside the ranking functions —
candidates are passed in pre-assembled by the CLI orchestrator.
"""

from __future__ import annotations

import json
import os
import sys
from typing import Dict, List, Set

BACKEND = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
if BACKEND not in sys.path:
    sys.path.insert(0, BACKEND)

# Type: candidates: Dict[pid, Dict[market_cap, volume_24h, circulating, total]]
CandidateMap = Dict[str, Dict[str, float]]


def rank_by_market_cap(candidates: CandidateMap, exclude: Set[str] = frozenset()) -> List[str]:
    pids = [p for p in candidates if p not in exclude]
    return sorted(pids, key=lambda p: candidates[p]["market_cap"], reverse=True)


def rank_by_fdv_mc_ratio(candidates: CandidateMap, exclude: Set[str] = frozenset()) -> List[str]:
    """Rank by total/circulating descending (high dilution overhang first)."""
    pids = [p for p in candidates if p not in exclude]
    return sorted(
        pids,
        key=lambda p: candidates[p]["total"] / max(candidates[p]["circulating"], 1e-12),
        reverse=True,
    )


def rank_by_turnover(candidates: CandidateMap, exclude: Set[str] = frozenset()) -> List[str]:
    """Rank by volume_24h / market_cap ascending (low velocity first)."""
    pids = [p for p in candidates if p not in exclude]
    return sorted(
        pids,
        key=lambda p: candidates[p]["volume_24h"] / max(candidates[p]["market_cap"], 1e-12),
    )


def curate_universe(
    candidates: CandidateMap,
    *,
    n_large: int = 15,
    n_mid: int = 15,
    n_high_fdv_ratio: int = 10,
    n_low_turnover: int = 10,
) -> Dict[str, List[str]]:
    """Apply Q5 criteria. Returns {'large', 'mid', 'high_fdv_ratio', 'low_turnover'}.

    Cohorts are filled in order: large, mid, high_fdv_ratio, low_turnover.
    Each cohort excludes pids already picked by earlier cohorts.
    """
    by_mc = rank_by_market_cap(candidates)
    large = by_mc[:n_large]
    mid = by_mc[n_large : n_large + n_mid]
    picked: Set[str] = set(large) | set(mid)

    high_fdv = rank_by_fdv_mc_ratio(candidates, exclude=picked)[:n_high_fdv_ratio]
    picked.update(high_fdv)

    low_turnover = rank_by_turnover(candidates, exclude=picked)[:n_low_turnover]

    return {
        "large": large,
        "mid": mid,
        "high_fdv_ratio": high_fdv,
        "low_turnover": low_turnover,
    }


def _assemble_candidates_from_local(
    *,
    inventory_json_path: str,
    supply_parquet_path: str,
    marketcap_dir: str,
    min_history_days: int = 180,
) -> CandidateMap:
    """Build the candidate pool from local files.

    A pid enters the pool when ALL hold:
      - inventory shows >= min_history_days of 1h OHLCV
      - supply snapshot has the pid (so circ/total are known)
      - marketcap parquet has at least one row (for current MC + volume)
    """
    import pyarrow.parquet as pq

    from tools.strategy_discovery.build_supply_snapshot import load_snapshot

    with open(inventory_json_path, "r", encoding="utf-8") as f:
        inv = json.load(f)
    history_inv = inv.get("history", {})

    supply_rows = {r["pid"]: r for r in load_snapshot(supply_parquet_path)}

    out: CandidateMap = {}
    for pid, hist in history_inv.items():
        days = (int(hist["last_ts"]) - int(hist["first_ts"])) // 86400
        if days < min_history_days:
            continue
        if pid not in supply_rows:
            continue
        mc_path = os.path.join(marketcap_dir, f"{pid}.parquet")
        if not os.path.exists(mc_path):
            continue
        table = pq.read_table(mc_path, columns=["market_cap", "volume_24h"])
        cols = table.to_pydict()
        if not cols["market_cap"]:
            continue
        out[pid] = {
            "market_cap": float(cols["market_cap"][-1]),
            "volume_24h": float(cols["volume_24h"][-1]),
            "circulating": float(supply_rows[pid]["circulating"]),
            "total": float(supply_rows[pid]["total"]),
        }
    return out


def _render_universe_md(picked: Dict[str, List[str]], candidates: CandidateMap) -> str:
    lines = [
        "# Strategy-Discovery Universe (50 pids)",
        "",
        "Generated by `tools/strategy_discovery/curate_universe.py` per Q5 of the "
        "2026-05-23 brainstorm spec.",
        "",
        "## Criteria (locked from Q5)",
        "",
        "- ~15 large-cap (top by market_cap)",
        "- ~15 mid-cap (next by market_cap)",
        "- ~10 high FDV/MC = total / circulating (high dilution overhang)",
        "- ~10 low turnover = volume_24h / market_cap (low velocity)",
        "- All filtered to >= 6 months 1h OHLCV + CoinPaprika supply data",
        "",
    ]
    for cohort, pids in picked.items():
        lines.append(f"## {cohort}  ({len(pids)} pids)")
        lines.append("")
        lines.append("| pid | market_cap | volume_24h | total/circ | vol/MC |")
        lines.append("|---|---:|---:|---:|---:|")
        for pid in pids:
            c = candidates[pid]
            ratio = c["total"] / max(c["circulating"], 1e-12)
            turnover = c["volume_24h"] / max(c["market_cap"], 1e-12)
            lines.append(
                f"| {pid} | {c['market_cap']:,.0f} | {c['volume_24h']:,.0f} "
                f"| {ratio:.3f} | {turnover:.4f} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    """CLI: read local inventory + supply + marketcap, curate, write outputs."""
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--inventory-json",
        default=os.path.join(
            BACKEND, "..", "docs", "superpowers", "specs", "2026-05-23-data-inventory.json"
        ),
    )
    parser.add_argument(
        "--supply-parquet",
        default=os.path.join(BACKEND, "data", "supply", "snapshot.parquet"),
    )
    parser.add_argument(
        "--marketcap-dir",
        default=os.path.join(BACKEND, "data", "marketcap"),
    )
    parser.add_argument(
        "--out-md",
        default=os.path.join(
            BACKEND, "..", "docs", "superpowers", "specs", "2026-05-23-universe-50.md"
        ),
    )
    parser.add_argument(
        "--out-json",
        default=os.path.join(
            BACKEND, "..", "docs", "superpowers", "specs", "2026-05-23-universe-50.json"
        ),
    )
    parser.add_argument("--n-large", type=int, default=15)
    parser.add_argument("--n-mid", type=int, default=15)
    parser.add_argument("--n-high-fdv-ratio", type=int, default=10)
    parser.add_argument("--n-low-turnover", type=int, default=10)
    parser.add_argument("--min-history-days", type=int, default=180)
    args = parser.parse_args()

    print("  assembling candidates from local data...", flush=True)
    candidates = _assemble_candidates_from_local(
        inventory_json_path=args.inventory_json,
        supply_parquet_path=args.supply_parquet,
        marketcap_dir=args.marketcap_dir,
        min_history_days=args.min_history_days,
    )
    print(f"  candidate pool: {len(candidates)} pids", flush=True)

    picked = curate_universe(
        candidates,
        n_large=args.n_large,
        n_mid=args.n_mid,
        n_high_fdv_ratio=args.n_high_fdv_ratio,
        n_low_turnover=args.n_low_turnover,
    )
    n_total = sum(len(v) for v in picked.values())
    print(f"  picked: {n_total} pids across {len(picked)} cohorts", flush=True)

    md = _render_universe_md(picked, candidates)
    os.makedirs(os.path.dirname(args.out_md), exist_ok=True)
    with open(args.out_md, "w", encoding="utf-8") as f:
        f.write(md)
    with open(args.out_json, "w", encoding="utf-8") as f:
        json.dump(picked, f, indent=2)

    print(f"  wrote: {args.out_md}", flush=True)
    print(f"  wrote: {args.out_json}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
